global:
  env: production
  valuesFile: values-production.yaml
  spec:
    project: production


argocdApplications:
  helmGuestbook:
    targetRevision: 1.0.0

  kustomizeGuestbook:
    disable: true

  syncWaves:
    disableAutomated: true
