global:
  env: production
  valuesFile: values-production.yaml
  spec:
    project: production


argocdApplications:
  helmGuestbook:
    targetRevision: rev

  kustomizeGuestbook:
    disable: true

  syncWaves:
    disableAutomated: true
